# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9rANFyxwa7Es9wCDwbNCTlgkTe2r7X9
"""

import numpy as np

# Definir las entradas y las salidas deseadas para la compuerta AND
entradas = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
salidas = np.array([0, 1, 1, 1])

# Inicializar pesos y bias
b = 0
w1 = 0.3
w2 = 0.3

# Definir la tasa de aprendizaje
learning_rate = 0.05




# Definir la función de activación step
def step(x):
    return 1 if x >= 0 else 0

# Entrenamiento del perceptrón
def entrenar_perceptron(entradas, salidas, b, w1, w2, learning_rate):
    errores = True
    iteracion = 0

    while errores:
        errores = False
        iteracion += 1
        print(f"Iteración {iteracion}:")

        for i in range(len(entradas)):
            x1, x2 = entradas[i]
            y_real = salidas[i]

            # Calcular la salida del perceptrón
            y_predicho = step(b + w1 * x1 + w2 * x2)

            # Calcular los errores y actualizar los pesos y bias si es necesario
            if y_real != y_predicho:
                errores = True
                error = y_real - y_predicho
                w1 = w1 + learning_rate * error * x1
                w2 = w2 + learning_rate * error * x2
                b = b + learning_rate * error

            print(f"    Entrada: {x1, x2}, Salida esperada: {y_real}, Salida predicha: {y_predicho}")
            print(f"    Pesos actualizados: b = {b:.3f}, w1 = {w1:.3f}, w2 = {w2:.3f}")

        print()

    return b, w1, w2

# Entrenar el perceptrón
b_final, w1_final, w2_final = entrenar_perceptron(entradas, salidas, b, w1, w2, learning_rate)

print("Entrenamiento completo.")
print(f"Pesos finales: b = {b_final:.3f}, w1 = {w1_final:.3f}, w2 = {w2_final:.3f}")

# Dibujo del resultado
import matplotlib.pyplot as plt
import numpy as np

# Datos de las entradas y salidas
entradas = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
salidas = np.array([0, 1, 1, 1])

# Pesos y bias finales obtenidos del entrenamiento: b_final, w1_final, w2_final


# Dibujar los puntos
for i in range(len(entradas)):
    x1, x2 = entradas[i]
    y = salidas[i]
    color = 'red' if y == 1 else 'blue'
    plt.scatter(x1, x2, color=color)

# Dibujar la recta de separación
# La ecuación de la recta es b + w1 * x1 + w2 * x2 = 0
# Despejamos x2 para dibujar la recta: x2 = -(b + w1 * x1) / w2

x = np.linspace(-0.1, 1.1, 100)
y = -(b_final + w1_final * x) / w2_final
plt.plot(x, y, '-g', label='Línea de decisión')

# Configuraciones adicionales del gráfico
plt.xlim(-0.1, 1.1)
plt.ylim(-0.1, 1.1)
plt.xlabel('x1')
plt.ylabel('x2')
plt.title('Perceptrón - Compuerta AND')
plt.axhline(0, color='black',linewidth=0.5)
plt.axvline(0, color='black',linewidth=0.5)
plt.grid(color = 'gray', linestyle = '--', linewidth = 0.5)
plt.legend()
plt.show()